# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  We are currently not accepting any contributions to this app. You can raise a feature request from [here](https://github.com/integrations/slack/issues/new)
