#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

PATH="$PATH:node_modules/.bin"

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

echo "==> Installing npm dependencies…"
npm install

# dev
sequelize db:create || true
sequelize db:migrate

# test
sequelize db:create --env test || true
sequelize db:migrate --env test
