name: GitHub CI

on: [push, pr]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      env:
        NODE_ENV: test
      with:
        version: 10.x
    - name: npm install, build
      env:
        NODE_ENV: test
        DB_USERNAME_TEST: "postgres"
      run: |
        npm install
        ./node_modules/.bin/sequelize db:create --env test
        ./node_modules/.bin/sequelize db:migrate --env test
    - name: npm test
      env:
        NODE_ENV: test
        DB_USERNAME_TEST: "postgres"
      run: |
        npm test
    services:
      postgresql:
        image: postgres
        ports:
        - 5432:5432
      redis:
        image: redis
        ports:
        - 6379:6379
